import Image from "next/image";
const projects=[
{slug:"the-bear-house-pacific-jaipur",name:"The Bear House — Pacific Mall Jaipur",meta:"1,916 SQ FT · JAIPUR",images:["/projects/bear-house-jaipur/01.jpg","/projects/bear-house-jaipur/02.jpg","/projects/bear-house-jaipur/03.jpg","/projects/bear-house-jaipur/04.jpg"]},
{slug:"vox-turquoise-mumbai",name:"VOX — Turquoise Mumbai",meta:"471 SQ FT · MUMBAI",images:["/projects/vox-mumbai/01.jpg","/projects/vox-mumbai/02.jpg","/projects/vox-mumbai/03.jpg","/projects/vox-mumbai/04.jpg"]},
{slug:"the-bear-house-m3m",name:"The Bear House — M3M Paragon 57",meta:"RETAIL INTERIOR · M3M",images:["/projects/bear-house-m3m/01.jpg","/projects/bear-house-m3m/02.jpg","/projects/bear-house-m3m/03.jpg","/projects/bear-house-m3m/04.jpg"]}];

const marqueeWords=["Retail interiors","GFC drawings","MEP coordination","Site execution"];

export default function Home(){return <main className="shell">
<nav className="nav"><a href="/">MR / 26</a><div className="navlinks"><a href="/">About</a><a href="/projects">Work</a><a href="/contact">Contact</a></div></nav>
<section className="aboutHero">
<div><div className="eyebrow">Civil Engineer / Retail Interior Designer</div><h1>Muhammad<br/>Rishad</h1><p className="lead">I work across retail interiors, technical documentation and site execution — translating design intent into spaces that can actually be built.</p><div className="heroActions"><a className="cta" href="/projects">View selected work <span>↗</span></a><a className="textlink" href="mailto:rishad.muhammad313@gmail.com">Start a conversation</a></div></div>
<div className="profileVisual"><Image src="/projects/bear-house-jaipur/01.jpg" alt="The Bear House Pacific Mall Jaipur retail interior" fill priority sizes="(max-width: 800px) 100vw, 42vw" style={{objectFit:"cover"}}/><div className="imageLabel">01 / SELECTED WORK</div></div>
</section>
<div className="marquee" aria-hidden="true"><div className="marqueeTrack">{[0,1].map(k=><div className="marqueeGroup" key={k}>{marqueeWords.map(w=><span key={w}>{w}<i>·</i></span>)}</div>)}</div></div>
<section className="introBand reveal"><div className="eyebrow">The approach</div><div className="statement">DESIGN ISN'T JUST ABOUT HOW A SPACE LOOKS. IT'S ABOUT HOW IT GETS BUILT.</div></section>
<section className="bioGrid section"><div className="eyebrow">Profile</div><div><p className="copy">With a Civil Engineering background and 2+ years across retail and commercial environments, Rishad combines space planning with construction drawings, coordination, QA/QC and site execution.</p><p className="copy muted">His work sits between design intent and on-site reality: developing retail layouts, construction drawings and coordinated technical packages while keeping buildability, customer movement and execution in focus.</p></div></section>
<section className="section reveal"><div className="sectionhead"><h2>Selected work</h2><a className="textlink" href="/projects">All projects ↗</a></div><div className="homeProjects">{projects.map((p,i)=><a className="homeProject" href={"/projects/"+p.slug} key={p.slug}><div className="homeProjectImage"><div className="slideshow">{p.images.map((src:string,j:number)=><Image key={src} src={src} alt={p.name+" view "+(j+1)} fill sizes="(max-width: 800px) 92vw, 34vw" style={{objectFit:"cover"}} className="slideImage"/>)}</div><span>{String(i+1).padStart(2,"0")}</span></div><div className="homeProjectMeta"><div><strong>{p.name}</strong><p className="projectDesc">{p.slug==="the-bear-house-pacific-jaipur"?"A warm, contemporary retail environment developed through fixture planning and detailed coordination across lighting, power, audio, security, POS and MEP requirements.":p.slug==="vox-turquoise-mumbai"?"A compact 471 sq ft retail space where disciplined planning and GFC documentation turn a small footprint into a clear, considered customer experience.":"A retail interior explored through spatial planning, 3D visualization and technical development, balancing brand expression with practical execution."}</p></div><small>{p.meta}</small></div></a>)}</div></section>
<section className="section capabilities reveal"><div className="sectionhead"><h2>Capabilities</h2></div><div className="capGrid"><div><b>01</b><h3>Retail design</h3><p>Space planning and design development for retail environments.</p></div><div><b>02</b><h3>Technical documentation</h3><p>Construction drawings and coordinated documentation.</p></div><div><b>03</b><h3>Execution</h3><p>Site coordination, QA/QC and practical buildability.</p></div></div></section>
<footer className="footer"><span>Muhammad Rishad</span><span>Bangalore · India</span><span>© 2026</span></footer>
</main>}